//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaxAcDesign.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class App {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal App() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PaxAcDesign.Resources.App", typeof(App).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип самолёта.
        /// </summary>
        public static string AircraftType {
            get {
                return ResourceManager.GetString("AircraftType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Результат вычисления первого блока.
        /// </summary>
        public static string Block1Result {
            get {
                return ResourceManager.GetString("Block1Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Самолет бизнес-класса.
        /// </summary>
        public static string BusinessJet {
            get {
                return ResourceManager.GetString("BusinessJet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Степень двухконтурности.
        /// </summary>
        public static string BypassRatio {
            get {
                return ResourceManager.GetString("BypassRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вычислить.
        /// </summary>
        public static string Calculate {
            get {
                return ResourceManager.GetString("Calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Город.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чистый аэродинамический профиль.
        /// </summary>
        public static string CleanAirfoil {
            get {
                return ResourceManager.GetString("CleanAirfoil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрылок с двумя прорезями.
        /// </summary>
        public static string DoubleSlottedFlap {
            get {
                return ResourceManager.GetString("DoubleSlottedFlap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрылок с двумя прорезями и предкрылок.
        /// </summary>
        public static string DoubleSlottedFlapAndSlat {
            get {
                return ResourceManager.GetString("DoubleSlottedFlapAndSlat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Двухкрылые юнкерсы.
        /// </summary>
        public static string DoubleWingJunkers {
            get {
                return ResourceManager.GetString("DoubleWingJunkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные о сотруднике.
        /// </summary>
        public static string Employee_Data {
            get {
                return ResourceManager.GetString("Employee Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип двигателя.
        /// </summary>
        public static string EngineType {
            get {
                return ResourceManager.GetString("EngineType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Женщина.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Параметры для шага №.
        /// </summary>
        public static string FieldsetDescription {
            get {
                return ResourceManager.GetString("FieldsetDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Истребитель.
        /// </summary>
        public static string Fighter {
            get {
                return ResourceManager.GetString("Fighter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрылок Фаулера.
        /// </summary>
        public static string FowlerFlap {
            get {
                return ResourceManager.GetString("FowlerFlap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрылок Фаулера и предкрылок.
        /// </summary>
        public static string FowlerFlapAndSlat {
            get {
                return ResourceManager.GetString("FowlerFlapAndSlat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пол.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Высота над уровнем моря.
        /// </summary>
        public static string HeightAboveSeaLevel {
            get {
                return ResourceManager.GetString("HeightAboveSeaLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип механизации крыла (закрылок и предкрылок).
        /// </summary>
        public static string HighLiftDevice {
            get {
                return ResourceManager.GetString("HighLiftDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата приема на работу.
        /// </summary>
        public static string Joining_Date {
            get {
                return ResourceManager.GetString("Joining Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Посадочный путь.
        /// </summary>
        public static string LandingDistance {
            get {
                return ResourceManager.GetString("LandingDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Большая дистанция.
        /// </summary>
        public static string LongRange {
            get {
                return ResourceManager.GetString("LongRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Реактивный самолет большой дальности полета.
        /// </summary>
        public static string LongRangeJetTransport {
            get {
                return ResourceManager.GetString("LongRangeJetTransport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мужчина.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отношение максимальной посадочной массы к максимальной взлетной массе.
        /// </summary>
        public static string MaxLandingMassToMaxTakeOffMassRatio {
            get {
                return ResourceManager.GetString("MaxLandingMassToMaxTakeOffMassRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Максимальный коэффициент подъемной силы.
        /// </summary>
        public static string MaxLiftCoefficient {
            get {
                return ResourceManager.GetString("MaxLiftCoefficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Максимальный коэффициент подъемной силы с закрылками во взлетном положении.
        /// </summary>
        public static string MaxLiftCoefficientTakeOff {
            get {
                return ResourceManager.GetString("MaxLiftCoefficientTakeOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Максимальная нагрузка на крыло.
        /// </summary>
        public static string MaxWingLoading {
            get {
                return ResourceManager.GetString("MaxWingLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Средняя дистанция.
        /// </summary>
        public static string MediumRange {
            get {
                return ResourceManager.GetString("MediumRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Реактивный самолет средней дальности полета.
        /// </summary>
        public static string MediumRangeJetTransport {
            get {
                return ResourceManager.GetString("MediumRangeJetTransport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Следующий шаг.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество двигателей.
        /// </summary>
        public static string NumberOfEngines {
            get {
                return ResourceManager.GetString("NumberOfEngines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Простой закрылок.
        /// </summary>
        public static string PlainFlap {
            get {
                return ResourceManager.GetString("PlainFlap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Простой закрылок и предкрылок.
        /// </summary>
        public static string PlainFlapAndSlat {
            get {
                return ResourceManager.GetString("PlainFlapAndSlat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предыдущий шаг.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные о двигателе.
        /// </summary>
        public static string RequestEngine {
            get {
                return ResourceManager.GetString("RequestEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные о запросе.
        /// </summary>
        public static string RequestPurpose {
            get {
                return ResourceManager.GetString("RequestPurpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарплата.
        /// </summary>
        public static string Salary {
            get {
                return ResourceManager.GetString("Salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите пол.
        /// </summary>
        public static string Select_Gender {
            get {
                return ResourceManager.GetString("Select Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите тип самолёта.
        /// </summary>
        public static string SelectAircraftType {
            get {
                return ResourceManager.GetString("SelectAircraftType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите тип двигателя.
        /// </summary>
        public static string SelectEngineType {
            get {
                return ResourceManager.GetString("SelectEngineType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите тип механизации крыла.
        /// </summary>
        public static string SelectHighLiftDevice {
            get {
                return ResourceManager.GetString("SelectHighLiftDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Короткая дистанция.
        /// </summary>
        public static string ShortRange {
            get {
                return ResourceManager.GetString("ShortRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Реактивный самолет малой дальности полета.
        /// </summary>
        public static string ShortRangeJetTransport {
            get {
                return ResourceManager.GetString("ShortRangeJetTransport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрылок с одной прорезью.
        /// </summary>
        public static string SingleSlottedFlap {
            get {
                return ResourceManager.GetString("SingleSlottedFlap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрылок с одной прорезью и предкрылок.
        /// </summary>
        public static string SingleSlottedFlapAndSlat {
            get {
                return ResourceManager.GetString("SingleSlottedFlapAndSlat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предкрылок.
        /// </summary>
        public static string Slat {
            get {
                return ResourceManager.GetString("Slat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разделенный закрылок.
        /// </summary>
        public static string SplitFlap {
            get {
                return ResourceManager.GetString("SplitFlap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шаг.
        /// </summary>
        public static string Step {
            get {
                return ResourceManager.GetString("Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сверхзвуковой крейсерский самолет.
        /// </summary>
        public static string SupersonicCruise {
            get {
                return ResourceManager.GetString("SupersonicCruise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Путь по земле при взлете.
        /// </summary>
        public static string TakeOffGroundRoll {
            get {
                return ResourceManager.GetString("TakeOffGroundRoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коэффициент зависимости тяговооружённости от нагрузки на крыло.
        /// </summary>
        public static string ThrustToWeightRatioAndWingLoadingCoefficient {
            get {
                return ResourceManager.GetString("ThrustToWeightRatioAndWingLoadingCoefficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Туториал от {0}.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Турбореактивный двигатель.
        /// </summary>
        public static string Turbojet {
            get {
                return ResourceManager.GetString("Turbojet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Турбовинтовой двигатель.
        /// </summary>
        public static string Turboprop {
            get {
                return ResourceManager.GetString("Turboprop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сверхбольшая дистанция.
        /// </summary>
        public static string UltraLongRange {
            get {
                return ResourceManager.GetString("UltraLongRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Реактивный самолет сверхбольшой дальности полета.
        /// </summary>
        public static string UltraLongRangeJetTransport {
            get {
                return ResourceManager.GetString("UltraLongRangeJetTransport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Соотношение сторон крыла.
        /// </summary>
        public static string WingAspectRatio {
            get {
                return ResourceManager.GetString("WingAspectRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отношение площади смачивания самолета к площади крыла.
        /// </summary>
        public static string WingWettedArea {
            get {
                return ResourceManager.GetString("WingWettedArea", resourceCulture);
            }
        }
    }
}
